import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import Message from "../components/Message";
import { db } from "../firebase";

export default function Home() {
  const [allPosts, setAllPost] = useState([]);

  const getPosts = async () => {
    const conlletionRef = collection(db, "posts");
    const q = query(conlletionRef, orderBy("timestamp", "desc"));
    const unscubscribe = onSnapshot(q, (snapshot) => {
      setAllPost(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    });
    return unscubscribe;
  };

  useEffect(() => {
    getPosts();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-12 text-lg font-medium">
        <h1>See what other people life</h1>
        {allPosts.map((post) => (
          <Message key={post.id} {...post}>
            <Link href={{ pathname: `/${post.id}`, query: post }}>
              <button className="text-gray-400 cursor-pointer">
                {post?.comments?.length} comments
              </button>
            </Link>
          </Message>
        ))}
      </div>
    </>
  );
}
